#!/usr/bin/perl
#======================================================================
#                    L I B / A N T S L I B 
#                    doc: Wed May 16 06:19:16 2012
#                    dlm: Wed Oct 29 19:22:45 2014
#                    (c) 2012 A.M. Thurnherr
#                    uE-Info: 35 42 NIL 0 0 72 0 2 4 NIL ofnI
#======================================================================

# HISTORY:
#	May 16, 2012: - created for V5.0
#	Oct 29, 2014: - made it work again for V6

($ANTSLIB) = ($0 =~ m{^(.*)/[^/]*$});

require "$ANTSLIB/ants.pl";
require "$ANTSLIB/libCPT.pl";
require "$ANTSLIB/libEOS83.pl";
require "$ANTSLIB/libGM.pl";
require "$ANTSLIB/libLADCP.pl";
require "$ANTSLIB/libNODC.pl";
require "$ANTSLIB/libPOSIX.pl";
require "$ANTSLIB/libRWalk.pl";
require "$ANTSLIB/libWOCE.pl";
require "$ANTSLIB/libWOCE_oldstyle.pl";
require "$ANTSLIB/libconv.pl";
require "$ANTSLIB/libfuns.pl";
require "$ANTSLIB/libgamma.pl";
require "$ANTSLIB/libstats.pl";
require "$ANTSLIB/libtides.pl";
require "$ANTSLIB/libubtest.pl";
require "$ANTSLIB/libvec.pl";

chomp($about = `sed -n '/^description =/s/description = //p' $ANTSLIB/.hg/hgrc`);
printf(STDERR "$about (\$antsLibVersion = %.1f) installed in $ANTSLIB\n",$antsLibVersion);
exit(0);
