#!/usr/bin/perl
#======================================================================
#                    A N T S L I B 
#                    doc: Wed May 16 06:19:16 2012
#                    dlm: Mon Apr 13 11:18:17 2020
#                    (c) 2012 A.M. Thurnherr
#                    uE-Info: 19 103 NIL 0 0 72 0 2 4 NIL ofnI
#======================================================================

# HISTORY:
#	May 16, 2012: - created for V5.0
#	Oct 29, 2014: - made it work again for V6
#	Oct 30, 2014: - changed output
#				  - added version check
#	Apr  5, 2015: - removed loading of most libraries
#				  - BUG: version consistency check works only on woosher

($ANTSLIB) = ($0 =~ m{^(.*)/[^/]*$});
$antsMinLibVersion = 6.0;						# don't change this; change antsLibVersion in [ants.pl]

require "$ANTSLIB/ants.pl";
#require "$ANTSLIB/libCPT.pl";
#require "$ANTSLIB/libEOS83.pl";
#require "$ANTSLIB/libGM.pl";
#require "$ANTSLIB/libLADCP.pl";
#require "$ANTSLIB/libNODC.pl";
#require "$ANTSLIB/libPOSIX.pl";
#require "$ANTSLIB/libRWalk.pl";
#require "$ANTSLIB/libWOCE.pl";
#require "$ANTSLIB/libWOCE_oldstyle.pl";
#require "$ANTSLIB/libconv.pl";
#require "$ANTSLIB/libfuns.pl";
#require "$ANTSLIB/libgamma.pl";
#require "$ANTSLIB/libstats.pl";
#require "$ANTSLIB/libtides.pl";
#require "$ANTSLIB/libubtest.pl";
#require "$ANTSLIB/libvec.pl";

printf("$ANTSLIB: V%.1f\n",$antsLibVersion);
exit(0);
